### PR TITLE
Add Stackbit Integration

### PR DESCRIPTION
**Pull request by DarkoArnautov**
This pull request add's Stackbit to this Jekyll theme. It add's the stackbit.yaml file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.

You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/centrarium (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)

I think this is really valuable and is a very low impact addition on your existing theme structure. Pretty much just the stackbit.yaml file. If you have questions or feedback I'm happy to discuss.

Darko

### CODE REVIEW

**Comment by bencentra** [comment]
This is awesome! Happy to add the config file. One small note, it looks like by defaulting all the social posts to empty strings they end up appearing in the footer:

Screen Shot 2019-10-01 at 7 50 00 PM

If there's a way to fix that that would be perfect.

You caught me at a good time, thanks to [Hacktoberfest](https://hacktoberfest.digitalocean.com) I'm paying a bit more attention to GitHub than usual :)

**Comment by bencentra** [comment]
FYI I tried out the demo at the link you posted and it appears to be stuck in "Validating Theme", for maybe 30 minutes before I closed the window.

Screen Shot 2019-10-01 at 8 24 40 PM

**Comment by DarkoArnautov** [comment]
Thanks for your interesting.
Did you make some change in _config.yml?

**Comment by DarkoArnautov** [comment]
> This is awesome! Happy to add the config file. One small note, it looks like by defaulting all the social posts to empty strings they end up appearing in the footer:
> 
> Screen Shot 2019-10-01 at 7 50 00 PM
> 
> If there's a way to fix that that would be perfect.
> 
> You caught me at a good time, thanks to [Hacktoberfest](https://hacktoberfest.digitalocean.com) I'm paying a bit more attention to GitHub than usual :)

We can comment above Social setting in _config.yml

**Comment by DarkoArnautov** [comment]
Please kindly check current result.
Thank you.

**Comment by bencentra** [comment]
Looks correct this time, thanks!

**Pull request merged**
